#!/usr/bin/env bash

set -e

if ! helm schema-gen --help > /dev/null 2>&1; then
    echo "Please install helm schema-gen plugin to run the pre-commit hook! https://github.com/knechtionscoding/helm-schema-gen?tab=readme-ov-file#install"
    exit 1
fi

rc=0

for value_file in "${@}"; do
    schema_file=$(dirname "${value_file}")/values.schema.json
 
   resultat=$(helm schema-gen "$value_file")

    if ! cmp -s <(echo "$resultat") "$schema_file"; then
        echo "$resultat" > "$schema_file"
        rc=1
    fi
done

exit $rc